name: Deploy Frontend
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vijayambattu/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true vijayambattu/docker-react npm run test